- name: docker build and push
  hosts: local  
  become: yes  

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t image .
      args:
        chdir: /var/lib/jenkins/workspace/devsecops_pipeline

    - name: tag image
      command: docker tag image:latest devsecopswithansible.azurecr.io/petstore:latest 

    - name: Log in to Docker Registry
      community.docker.docker_login:
        registry_url: devsecopswithansible.azurecr.io
        username: devsecopswithansible
        password: APiSs7TzzqZgbaOHi3Qe1ddWQDexFkFrIomcXjWqQa+ACRDMIWSY

    - name: Push image
      command: docker push devsecopswithansible.azurecr.io/petstore:latest

    - name: Run container
      command: docker run -d --name pet -p 8081:8080 devsecopswithansible.azurecr.io/petstore:latest
